name: Hourly News Scraper

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: write

jobs:
  scrape-news:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pytz

      - name: Run scraper
        run: python scrape_reuters.py

      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update daily news"
          file_pattern: NEWS.md
          commit_user_name: "News Bot"
          commit_user_email: "newsbot@users.noreply.github.com"
          commit_author: "News Bot <newsbot@users.noreply.github.com>"